title: RegularJS
author: leeluolee
language: zh-cn
url: https://regularjs.org
root: /
permalink: blogs/:year/:month/:day/:title/
archive_dir: blogs
new_post_name: :year-:month-:day-:title.md
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: navy

google_analytics: UA-46698359-4
algolia:
  api_key: 365f3d88c244de5de6835c3f0f72b1ce
  index_name: regular
github:
  name: regularjs
  repo: regular
