<!-- GitHub Star -->
<iframe src="https://ghbtns.com/github-btn.html?user={{ config.github.name }}&repo={{ config.github.repo }}&type=star&count=true&v=2" frameborder="0" scrolling="0" width="110px" height="20px"></iframe>
<!-- GitHub fork -->
<iframe src="https://ghbtns.com/github-btn.html?user={{ config.github.name }}&repo={{ config.github.repo }}&type=fork&count=true&v=2" frameborder="0" scrolling="0" width="110px" height="20px"></iframe>